### ISSUE TITLE
Allow force-showing of cursor

### ISSUE THREAD

**Issue by pradyunsg** [karlhorky/BlockCursorEverywhere#10]
Would you consider adding a configuration option to force-show the cursor, regardless of whether Vintage or Vintagious are installed?

Something like `force_show_block_cursor_everywhere` in "User\Preferences.sublime-settings" maybe?

**Comment by cveneziani** [comment]
+1

**Comment by K4stor** [comment]
+1

**Comment by pradyunsg** [comment]
Bump.

**Comment by karlhorky** [comment]
I haven't had a chance to look at this. Would gladly look at a pull request for this though if you'd like to contribute.

**Comment by karlhorky** [comment]
Block cursor without Vintage or Vintageous been set as the default behavior in [`2.0.0`](https://github.com/karlhorky/BlockCursorEverywhere/releases/tag/v2.0.0) - no settings required.
