### ISSUE TITLE
3idesu [ESC] causes plugin crash in Vintageous

### ISSUE THREAD

**Issue by zjc0816** [karlhorky/BlockCursorEverywhere#11]
And it inserts lots of `desu `. When I disable `BlockCursorEverywhere`, it works normally.
```
Traceback (most recent call last):
  File "SublimeBlockCursor in /home/morecru/.config/sublime-text-3/Installed Packages/Block Cursor Everywhere.sublime-package", line 50, in on_command_mode_change
RuntimeError: maximum recursion depth exceeded
error: plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted
```

**Comment by karlhorky** [comment]
Yes, this is indeed a problem. I wonder if this has anything to with guillermooo/Vintageous#739

**Comment by karlhorky** [comment]
As mentioned in the other issue, using <kbd>a</kbd> instead of <kbd>i</kbd> seems to prevent the problem:

`3adesu <esc>`

@zjc0816 can you confirm?

**Comment by zjc0816** [comment]
Yes, I use <kbd>a</kbd> and it works.

**Comment by karlhorky** [comment]
I've fixed this in https://github.com/karlhorky/BlockCursorEverywhere/pull/12. Thanks for the bug report!
