### ISSUE TITLE
Theme file

### ISSUE THREAD

**Issue by leegee** [karlhorky/BlockCursorEverywhere#15]
The install instructions kindly explain the basics to noobs, but then mention a theme file to be updated -- it'd hellp if that was explained in as much detail as Package Control.

tia...!
lee

**Comment by NeCkEr** [comment]
Where I can find the Theme file?? 
I installed it the package throught the `package manager` but then nothing happened.

Thanks

**Comment by You4eea** [comment]
leegee is correct,
This is topical for sublime plugins authors.. Although the readme looks and would seem complete, for noobs, it sucks... I have no idea how to edit the theme file.. I made an attempt, but my cursor has not changed. 

But one thing you can cont on... if you don't know how to install package control, you will figure it out as a result of everyone plugin author has that in their readme... 

This is why I would never buy sublime, the documentation sucks and all the little switches you have to hunt for in google, forget ever getting a straight answer.. Like this post.. will never be really answers, much like leegees.. what kind of answer is that, you added some labeles.. Oh great.. that solves it.

thanks, but no thanks!
